# Generated by Django 6.0 on 2025-12-12 02:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
        ('fornecedores', '0001_initial'),
        ('marcas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('unidade_medida', models.CharField(choices=[('UN', 'Unidade'), ('G', 'Grama'), ('KG', 'Quilo'), ('L', 'Litro'), ('CX', 'Caixa'), ('PAC', 'Pacote'), ('MT', 'Metro')], default='UN', max_length=10)),
                ('preco_custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque_minimo', models.IntegerField(default=0)),
                ('estoque_atual', models.IntegerField(default=0)),
                ('data_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='categorias.categoria')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='fornecedores.fornecedor')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='marcas.marca')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
