# Generated by Django 6.0 on 2025-12-12 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movimentacoes', '0001_initial'),
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entradaestoque',
            name='usuario_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entradaitem',
            name='entrada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='movimentacoes.entradaestoque'),
        ),
        migrations.AddField(
            model_name='entradaitem',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entrada_itens', to='produtos.produto'),
        ),
        migrations.AddField(
            model_name='saidaestoque',
            name='usuario_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='saidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saidaitem',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saida_itens', to='produtos.produto'),
        ),
        migrations.AddField(
            model_name='saidaitem',
            name='saida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='movimentacoes.saidaestoque'),
        ),
    ]
