# Generated by Django 6.0 on 2025-12-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nivel_acesso',
            field=models.CharField(choices=[('admin', 'Admin'), ('estoquista_prateleira', 'Estoquista'), ('caixa', 'Caixa')], default='estoquista_prateleira', max_length=30, verbose_name='Nível de acesso'),
        ),
    ]
