# Generated by Django 6.0 on 2025-12-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_nivel_acesso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nivel_acesso',
            field=models.CharField(choices=[('admin', 'Admin'), ('estoquista', 'Estoquista'), ('caixa', 'Caixa')], default='estoquista', max_length=30, verbose_name='Nível de acesso'),
        ),
    ]
