# Generated by Django 6.0 on 2025-12-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_nivel_acesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='avatar',
            field=models.CharField(choices=[('homem', 'Homem'), ('mulher', 'Mulher')], default='homem', max_length=10, verbose_name='Avatar'),
        ),
    ]
